### ISSUE TITLE
index.html 无法播放，但是1.mp4的文件是对的

### ISSUE THREAD

**Issue by waiter89** [Akagi201/learning-webrtc#1]
closed
index.html:25 open
index.html:38 ws://192.168.100.17:8081/1.mp4
index.html:42 connected
index.html:30 Uncaught InvalidStateError: Failed to execute 'endOfStream' on 'MediaSource': The MediaSource's readyState is not 'open'.(anonymous function) @ websocketvideotest.html:30
6websocketvideotest.html:34 Uncaught InvalidStateError: Failed to execute 'appendBuffer' on 'SourceBuffer': This SourceBuffer has been removed from the parent media source.(anonymous function) @ index.html:34ws.onmessage @ index.html:45
index.html:48 closed

**Comment by Akagi201** [comment]
@waiter89 1.mp4 是 fMP4 吗?
