### ISSUE TITLE
codecs

### ISSUE THREAD

**Issue by MrZhouZh** [Akagi201/learning-webrtc#2]
您好！菜鸟来请教：
codec是什么，
var audioSourceBuffer = mediaSource.addSourceBuffer('video/mp4;codecs="mp4a.40.2"');
var videoSourceBuffer = mediaSource.addSourceBuffer('video/mp4;codecs="avc1.42E01E"');
如果是其他格式的codecs呢？这个是自己手打，还是有手册可以查？望大神指教！

**Comment by Akagi201** [comment]
这个可以通过工具来查看. 具体工具可以参考我的 blog: http://akagi201.org/post/websocket-mse/

**Comment by MrZhouZh** [comment]
谢谢
